import Footer from './components/Footer';
import Navigation from './components/Navigation';
import { Web3Provider } from './components/Web3Provider';
import './globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rhyze and shine',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Web3Provider>{children}</Web3Provider>
        <Footer />
      </body>
    </html>
  );
}
